from pathlib import Path
chapters=[
('strange','01 / A STRANGE MACHINE','A wrong-looking start.',[
('Six numbers. One question.','Can a procedure that first puts the largest number at the front still finish with the smallest first? Keep your prediction in mind. Scroll to watch what happens.'),
('First, it does the suspicious thing.','The first round moves 6 to the front. That looks backwards. But one intermediate picture cannot tell you where a procedure will finish.'),
('Watch the boundary, not one number.','After the third round, the first three positions are ordered, with 6 at their right edge. That growing ordered section is the useful clue.'),
('The promise survives.','Each new value is inserted into the ordered section, and its maximum travels to the new boundary. At the last boundary, the whole list is ordered.'),
('A reason is stronger than a lucky example.','Stanley Fung described this surprising all-pairs algorithm in 2021. For each position, it visits every position and swaps when the first value is smaller. The preserved promise explains its result; a few successful examples alone would not. <a href="#source-fung">Read the source ↗</a>')]),
('image','02 / SAME PICTURE, DIFFERENT WORK','One destination. Different journeys.',[
('Give both methods the same job.','These eight strips belong to one illustration. Each carries a number specifying its correct position. The computer reads those numbers; it does not recognise mountains.'),
('Insertion reuses a growing ordered section.','Insertion sort takes the next strip and moves it left past larger neighbours. Notice how the smaller strips have gathered on the left.'),
('Merge combines ordered groups.','Merge sort builds ordered groups and combines them, taking the smaller front record next. It uses temporary storage. Here we show checkpoints where every strip is back in the main row.'),
('Same answer does not mean same work.','Both preserve all eight strips and reconstruct the picture. The counters show key comparisons and main-array writes for these teaching implementations. Scroll distance and animation duration are not measures of execution time.')]),
('choice','03 / BETTER FOR WHAT?','Change the input. Change the work.',[
('A shuffled list needs repair.','Compare insertion sort with selection sort, which repeatedly finds the smallest remaining item. For this small shuffled input, inspect the actual work before declaring a winner.'),
('Now give them almost-finished work.','Only two neighbours are out of place. Insertion can reuse the existing order. Selection still scans the unfinished section to find its minimum. The same input size does not imply the same work.'),
('Sometimes the keys offer a shortcut.','These strips have unique destination numbers from 1 to 8. With eight output slots, place each directly in its numbered slot: eight placements, plus output storage. A small, known key range changes the problem. For general records with duplicate integer keys, counting sort needs counts and assigned output positions.')]),
('records','04 / WHAT MUST SURVIVE?','An ordered column can still be wrong.',[
('Start with three real records.','An expense is more than its amount. “Groceries, ₹840” is one record. The amount is the sorting key. Its label must travel with it.'),
('Sort only the amounts.','The numbers now increase, but groceries suddenly cost ₹180 and the notebook ₹840. This is an ordered column and a broken set of records. Correct sorting must preserve their associations.'),
('Move whole records instead.','Now notebook, train and groceries remain attached to their original amounts. In Excel or Google Sheets, the practical lesson is to include the complete record range. We do not claim either product uses a particular internal sorting algorithm. <a href="#receipts">Explore ties and everyday examples ↗</a>')]),
('search','05 / WHERE AI ENTERS','Even tiny routines leave room to search.',[
('A plausible program can fail.','Here is a toy program: compare positions 1 and 2, then 2 and 3, exchanging values when they are reversed. It sorts some inputs. Testing all six orders of three distinct values reveals the failures.'),
('One more instruction fixes this toy.','Compare positions 1 and 2 again. All six inputs now pass. This is a classic three-comparison network, not an AI discovery. It illustrates the distinction between proposing a candidate and checking it.'),
('The real discovery was lower down.','In 2023, AlphaDev searched for faster small sorting routines at the assembly-instruction level; some were integrated into LLVM’s libc++ sorting implementation. It did not replace the whole field with one universal new sort. The lesson is that an old task can still hide opportunities when you change the representation and the operations available. <a href="#ai-discovery">Read the sourced AI account ↗</a>')])]
out=['''<section class="s-cover shell"><p class="j-tag">A GUIDED VISUAL STORY · SORTING</p><h1>This looks wrong.<br>It still <em>sorts.</em></h1><p class="s-dek">A scientist tried to write a bad sorting algorithm. It worked.<br>AI found better tiny routines. How was there still room to improve?</p><p class="s-promise">Follow the numbers. Leave with a way to think.</p><p class="s-scroll">↓ Just scroll. The illustrations follow the story.</p><nav aria-label="Story chapters">''']
for id,k,title,steps in chapters:out.append(f'<a href="#story-{id}">{k.split(" / ")[1].title()}</a>')
out.append('</nav><p class="s-small">Prefer experimenting? <a href="#practice">Open the hands-on playground</a> · Research through 13 September 2026</p></section><noscript><p class="shell">The complete text is readable below. Animated illustrations require JavaScript; the historical atlas remains available.</p></noscript>')
for id,k,title,steps in chapters:
 out.append(f'<section class="s-chapter shell" id="story-{id}" data-story="{id}"><header><p class="j-tag">{k}</p><h2>{title}</h2></header><div class="s-layout"><figure class="s-figure"><div class="s-figure-top"><span>{k.split(" / ")[1]}</span><span class="s-count">1 / {len(steps)}</span></div><div class="s-scene" role="img" aria-label="Illustration for this chapter"></div><figcaption class="s-caption">Scroll through the explanation to reveal each stage.</figcaption><div class="s-progress" aria-hidden="true"><span></span></div></figure><div class="s-prose">')
 for i,(h,p) in enumerate(steps):out.append(f'<article class="s-beat" data-beat="{i}"><span class="s-number">{i+1:02}</span><h3>{h}</h3><p>{p}</p></article>')
 out.append('</div></div></section>')
out.append('''<section class="s-ending shell"><p class="j-tag">TAKE THE HABIT WITH YOU</p><h2>Before asking “which algorithm?”,<br>ask “what is the job?”</h2><div class="s-takeaways"><p><b>Define the goal.</b><br>What does “ordered” mean here?</p><p><b>Protect the records.</b><br>What must stay attached or unchanged?</p><p><b>Use what you know.</b><br>Is there existing order or a limited key range?</p><p><b>Name the trade-off.</b><br>Time, storage, predictability—or something else?</p></div><p>Sorting is a useful first lesson in structured thinking because you can see the steps and check the result. It is not the whole of critical thinking: choosing a fair ranking or deciding whose needs matter requires judgment beyond arranging keys.</p><p>You have reached the end of the guided story. Try the experiments below, or <a href="#atlas">explore the historical atlas</a>.</p></section>''')
Path('research/sorting/scroll-story.html').write_text('\n'.join(out))
